### PR TITLE
QuantLSTM (ONNX) QCDQ representation

### PR DESCRIPTION
**Pull request by shashwat1198**
The notebook tutorial contains:

- QCDQ - (Quant) LSTM implementation with standard ONNX operators.
- 'Scan' ONNX operator usage to implement the QCDQ LSTM graph to enable inputs/weights/activation quantization and enable processing of multiple inputs.
- Functional verification of the 'scan' operator based QCDQ LSTM implementation with the 'QuantLSTM' model in brevitas.

### CODE REVIEW

**Comment by maltanar** [comment]
It seems this notebook is using some packages (at least `torch` and `brevitas`) which are not installed as part of `qonnx` by default. Can you please either add documentation or pip install commands in the notebook itself, also indicating which version(s) of these packages the notebook is tested with?

**Comment by shashwat1198** [comment]
Hey,

Sorry for the late response. I missed this message completely.

Sure sure. I will add some pip commands to install all the required
dependencies that are not installed with qonnx by the end of this week. I
have a deadline and that is why the delay.

Kind regards,
Shashwat

**Comment by shashwat1198** [comment]
Hey, I have updated the notebook with the required package installations. For the notebook to execute, there were two files that needed to be updated and copied within brevitas inside the qonnx vitrual environment. I have added those files in a separate folder named '4_quant_lstm_helper' folder.

**Comment by maltanar** [comment]
I finally got around to trying out the latest version and everything looks good, merging now. Thanks @shashwat1198 !

**Comment by shashwat1198** [comment]
Thank you so much for taking out the time to review the PR and to get it
merged.🙏

**Pull request merged**
