### PR TITLE
Fix FoldTransposeIntoQuantInit Transformation

### PR DESCRIPTION
**Pull request by iksnagreb**
Intends to fix problems related to the `FoldTransposeIntoQuantInit` transformation. The transformation should only be applied if the `Transpose` node actually follows a so called `QuantInit`, these are `Quant` (or `BipolarQuant`) nodes where **all** inputs are initializers. Currently, the transform is always applied, even if just _some_ inputs have initializers. This causes problems with the shape inference, as the remaining `Quant` node does not transpose its runtime inputs. This is fixed by making the test for a node being `QuantInit` more strict.

I have tested this by running the unit tests for QONNX as well as those under `tests/transformation` over at [FINN](https://github.com/Xilinx/finn) and did not observe any issues so far. For more context please see the following issues: #77, https://github.com/Xilinx/finn/issues/878, https://github.com/Xilinx/finn/issues/892.

### CODE REVIEW

**Comment by iksnagreb** [comment]
Hm, all tests fail? What is going on? Seems not to be my fault?

**Comment by iksnagreb** [comment]
I have just added a new unit test validating both situations, i.e., keeping and removing the `Transpose` node, as well as running the `InferShapes` transformation directly after `FoldTransposeIntoQuantInit`.

**Comment by iksnagreb** [comment]
Hm, again some unrelated tests fail. This time it is some `HTTP Error 500: INTERNAL SERVER ERROR`. However, all passed for the two commits in between, seems to be something external?

**Comment by maltanar** [comment]
The previous CI failures were due to an `onnxruntime` bug that got fixed last week, so `main` is now [updated](https://github.com/fastmachinelearning/qonnx/pull/76) to use the most recent version that takes care of that which I updated this PR with. 

The last CI failures seem to be due to some intermittent server failure, re-running was enough to make all tests pass.

Otherwise, the PR looks all good to me - thanks @iksnagreb ! I'll only add one comment here about this bit before I hit merge:

```
                        # Skip transposing the initializer if the number of
                        # dimensions do not match
                        if perm is not None and len(perm) != tensor.ndim:
                            # Note: Soft skip ok or is this an error?
                            continue
```
The only cases I've previously seen that would give a `perm` tensor with a different number of dimensions is when the tensor in question was a scalar (for instance a global zeropoint value of 0). This would be safe to skip. 

In theory, one could take advantage of shape broadcasting to create quantization parameters that are neither scalar nor matching the number of dimensions for the target tensor, as this is already mis-specified in the [Quant node spec](https://github.com/fastmachinelearning/qonnx/blob/main/docs/qonnx-custom-ops/quant_op.md). I'll update the Quant node spec to permit only scalar OR ndim == tensor ndim cases.

**Comment by iksnagreb** [comment]
Thank you!

**Pull request merged**
