### PR TITLE
Improved channels-last via elementwise op generalization

### PR DESCRIPTION
**Pull request by maltanar**
**Summary:** Improves the channels-last conversion in several aspects:

- Use the concept of elementwise ops to move `Transpose` nodes downstream in a more robust way, including non-linear (forking, residual etc) topologies. See detailed notes below.
- Handle cases where the `perm` attribute for `Transpose` nodes is not specified by using the ONNX default (invert order of axes).
- Other fixes and improvements to channels-last conversion of non-linear topologies: prevent upstream movement past forked nodes, instead introduce `MoveTransposePastFork` to move pre-fork ops into fork branches
- Add a ResNet-18 testcase for channels-last conversion.

### Elementwise ops for moving Transpose nodes more robustly

**Preliminaries**: An elementwise op is any ONNX (or QONNX) operator which operates on each element independently when producing its output from its inputs. Some examples (as implemented by a list of such optypes in this PR):

```
_eltwise_optypes = ["Relu", "Quant", "Mul", "Div", "Sub", "Add"]
```

Note that elementwise ops can have one or more inputs (e.g. `Relu` takes only one input, `Mul` takes two, and `Quant` takes four) and may support [numpy-style broadcasting](https://numpy.org/devdocs/user/basics.broadcasting.html). The inputs may be dynamic or come from initializers.

**Moving `Transpose` past elementwise ops:** This is a crucial step for channels-last conversion, as originally explained in [this slide deck](https://docs.google.com/presentation/d/11qxj_fV_6Dt4ar5pxGAHWvJxiwddyJKCAMSq_abbLVo/edit?usp=sharing). Because each element is treated independently for elementwise ops, we can make them use any ordering of the inputs and outputs as long as they are consistent with the original graph. To move a `Transpose` op past an elementwise op, we can think of applying the reverse transposition operation (given by the permutation of axis indices that would sort the original `Transpose` node's `perm` attribute) to each input and each output of the elementwise operator. For the input supplied by the original `Transpose` output, the two consecutive (inverse) transpositions now cancel each other out and disappear. To ensure cases with broadcasting are handled correctly, any inputs which use a tensor that will be broadcasted to the input dimension should be given dummy dimensions.

Several illustrations of the transformation are provided in the figure below.

image

### CODE REVIEW

**Comment by jmitrevs** [comment]
Do we still need `_move_through_nodes` and `_move_through_nodes_if_scalar`? I noticed they are still used in `MoveChanLastUpstream`.

**Comment by jmitrevs** [comment]
By the way, #148 adds more activations to what transposes can pass through. Maybe it can be incorporated here.

**Comment by maltanar** [comment]
> Do we still need `_move_through_nodes` and `_move_through_nodes_if_scalar`? I noticed they are still used in `MoveChanLastUpstream`.

Ideally we would remove them and just use the `_eltwise_optypes` but I see that `MoveChanLastUpstream` is making some assumption about the number of inputs to the op, only checking `input[1]`. So this probably needs some extra refactoring and testcases to check that moving to `_eltwise_optypes` does not break things, since e.g. `Quant` has multiple inputs.

```
                    if predecessor.op_type in _move_through_nodes_if_scalar:
                        second_inp_shape = model.get_tensor_shape(predecessor.input[1])
                        if second_inp_shape == [1] or second_inp_shape == []:
                            move_through_valid |= True
```

**Comment by maltanar** [comment]
I've added the changes from #148 into this one since they are well aligned, and moved the list of elementwise ops (and monotonic ops) to one of the utility modules, since that is a useful shared information for other transforms too. 

For now I've opted to keep the `_move_through_nodes(_if_scalar)`, but I actually think we can deprecate all that plus more in the future by using `move_transpose_past_eltwise` with the existing list of eltwise ops. Possibly we'll need the inverse tranformation of `move_transpose_past_eltwise` i.e. moving a transpose from output to all inputs as well, but once we have these bits the entire channels-last conversion could be vastly simplified.

**Pull request merged**
