### PR TITLE
Fix channels last conversion for Conv operators with a bias

### PR DESCRIPTION
**Pull request by jmitrevs**
As reported in #32, the channels-last conversion currently fails for Conv operators with a bias and gives:

```
AssertionError: Channels last conversion is only available for 3D and 4D tensors.
```

This attempts to solve the problem by simply skipping over the bias tensor for Conv operators.

### CODE REVIEW

**Comment by HenniOVP** [comment]
Hi Jovan,
that looks quite good so far!
And as far as I can tell the changes should work well for the channels last conversion. However, when using the resulting channels last node for node execution one might run into issues with the node verification. In particular the verification currently expects exactly 2 inputs for Conv nodes, but with a the bias input there are now three.
So this line should likely be changed to something like the following to pass the verification: https://github.com/fastmachinelearning/qonnx/blob/main/src/qonnx/custom_op/channels_last/conv.py#L143
`if len(node.input) == 2:`
to
`if (len(node.input) == 2) or (len(node.input) == 3):`
Along with adjusting the error message for the case when this if-statement evaluates to False.

**Comment by jmitrevs** [comment]
I think I fixed the node verification. Please take a look again.

**Comment by HenniOVP** [comment]
Hi Jovan,
I went ahead and tried to add the model you mentioned in the issue as a test case and the whole thing has gotten a bit more complicated that I had hoped. I've got it running now, but it required more changes than I had expected. Here is the branch with the working test: https://github.com/HenniOVP/qonnx/tree/channel-last-bias_testable

Things that needed changing in order of commit:
1. The MaxPool nodes in the model used optional attributes, so I added them to the node verification: faf88ba5cd6e3adc01a51b2ed2ecf64d7ca305c2
2. Folding the ChanFirst Transpose in front of a `Flatten -> Gemm` node construct is currently not supported so I added the `GemmToMatMul` conversion to the cleanup: 458383a89856c1c18d780773cf0c53ca289f0a6c
3. The `AbsorbChanFirstIntoMatMul` conversion only supported quantized inputs to the MatMul, not if the weights were directly in the initializer without any quant node in-between, so I added support for that: f4902e8130aaaab6f6a3caa96fcc47d2e6e30b5e
4. Added the actual test: 30a9e77b9ab40b33c19dfc866a1eefe8202f87e8

While change 1. is probably fine to upstream, I'm not too sure about 2. to 4.. In particular 2. might be counter to what some users expect the cleanup to do, which is to keep most nodes as they are. Number 3. is probably fine, but adds new complexity and 4. is debatable, because it's not actually a QONNX model that is being tested, but a pure ONNX one.

I think some discussion might be required to make sure that these changes are fine to be upstreamed.

**Comment by jmitrevs** [comment]
About the test, the input file is in a repository that was created to try out some things in hls4ml, and is not guaranteed to remain. For the test, it might make sense to copy the input file somewhere else.

**Comment by HenniOVP** [comment]
Yeah, that's probably a good idea for the future. 

Also for point 2. and 3., which I mentioned: One could maybe make the transformation also compatible with Gemm and not just MatMul. This would then mean that the Gemm won't need to be converted to a MatMul during the cleanup.

**Comment by jmitrevs** [comment]
So what is the plan? Should I add your commits to this PR?

**Comment by HenniOVP** [comment]
Hi,
I've now adapted the `AbsorbChanFirstIntoMatMul` transformation to also work with `Gemm` nodes, so that the conversion in the cleanup isn't required anymore. I think that is more in-line with how the cleanup utility should work.

The only open question is now: What do we do with the test case?
Should the model be moved elsewhere? And if so where? And also does it make sense to have a pure ONNX model as a test case?

**Comment by HenniOVP** [comment]
So I've tested the branch with the new changes from the `main` branch, where the onnx versions for the github actions and the package are the same. And it appears that now models are automatically run at the onnx opset version 9. Unfortunately this means that the super_resolution model, which is used by the new test won't work, since this uses a `MaxPool` node with attributes only introduced in version 10 of the opset.
@jmitrevs Do you think it would be possible to export the model again with opset version 9? Then the test should work fine.

**Comment by HenniOVP** [comment]
The tests now pass with the most recent changes to the main branch. @jmitrevs So no need to re-export the model anymore.
However, this raises the question of how different/newer opsets should be communicated effectively to the channels last ops.

**Pull request merged**
